calcule_distance_parallele:calcule_distance_parallele.c
	gcc -o calcule_distance_parallele calcule_distance_parallele.c -g -O0 -lm -lpthread -fopenmp 

run:calcule_distance_parallele
	./calcule_distance_parallele fichier.txt 
clean:
	rm  calcule_distance_parallele
